export interface PlanetConfig {
  id: string;
  name: string;
  label: string;
  texturePath: string;
  position: number;
  hasRings?: boolean;
  ringTexturePath?: string;
  ringInnerRadius?: number;
  ringOuterRadius?: number;
  ringColor?: string;
  ringOpacity?: number;
  ringRotation?: [number, number, number];
  scale?: number;
  displayScale?: number;
  infoScale?: number;
  infoDistance?: number;
  switchClass?: string;
  labelClass?: string;
  imageClass?: string;
  isMoon?: boolean;
  color?: string;
  orbitRadius?: number;    
  orbitSpeed?: number;     
  orbitColor?: string;     
}

export const PLANETS: PlanetConfig[] = [
  {
    id: 'sun',
    name: 'Sun',
    label: 'солнце',
    texturePath: '/assets/textures/8k_sun.jpg',
    position: 8,
    scale: 1.5,
    displayScale: 2.2,
    infoScale: 1.5,
    infoDistance: 7,
    switchClass: 'planetSwitchSun',
    labelClass: 'labelSun',
    color: '#FDB813',
    orbitRadius: 0,
    orbitSpeed: 0,
    orbitColor: '#FDB813',
  },
  {
    id: 'mercury',
    name: 'Mercury',
    label: 'меркурий',
    texturePath: '/assets/textures/8k_mercury.jpg',
    position: 17.33,
    scale: 0.8,
    displayScale: 0.6,
    infoScale: 1.0,
    infoDistance: 5.5,
    switchClass: 'planetSwitchMercury',
    labelClass: 'labelMercury',
    color: '#8C8C8C',
    orbitRadius: 3.5,
    orbitSpeed: 0.8,
    orbitColor: '#8C8C8C',
  },
  {
    id: 'venus',
    name: 'Venus',
    label: 'венера',
    texturePath: '/assets/textures/4k_venus.jpg',
    position: 26.67,
    scale: 0.85,
    displayScale: 0.85,
    infoScale: 1.4,
    infoDistance: 4.5,
    switchClass: 'planetSwitchVenus',
    labelClass: 'labelVenus',
    imageClass: 'ellipseVenus',
    color: '#E6B800',
    orbitRadius: 5.0,
    orbitSpeed: 0.6,
    orbitColor: '#E6B800',
  },
  {
    id: 'earth',
    name: 'Earth',
    label: 'земля',
    texturePath: '/assets/textures/8k_earth_daymap.jpg',
    position: 36,
    scale: 0.9,
    displayScale: 1.0,
    infoScale: 1.5,
    infoDistance: 4.5,
    switchClass: 'planetSwitchEarth',
    labelClass: 'labelEarth',
    imageClass: 'ellipseEarth',
    color: '#2271B3',
    orbitRadius: 6.5,
    orbitSpeed: 0.5,
    orbitColor: '#2271B3',
  },
  {
    id: 'mars',
    name: 'Mars',
    label: 'марс',
    texturePath: '/assets/textures/8k_mars.jpg',
    position: 45.33,
    scale: 0.85,
    displayScale: 0.75,
    infoScale: 1.4,
    infoDistance: 4.5,
    switchClass: 'planetSwitchMars',
    labelClass: 'labelMars',
    imageClass: 'ellipseMars',
    color: '#C1440E',
    orbitRadius: 8.0,
    orbitSpeed: 0.4,
    orbitColor: '#C1440E',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    label: 'юпитер',
    texturePath: '/assets/textures/8k_jupiter.jpg',
    position: 54.67,
    scale: 1.2,
    displayScale: 1.8,
    infoScale: 1.6,
    infoDistance: 5.0,
    hasRings: true,
    ringInnerRadius: 1.3,      
    ringOuterRadius: 1.7,
    ringColor: '#8B7355',
    ringOpacity: 0.15,
    ringRotation: [0.1, 0, 0.1],
    switchClass: 'planetSwitchJupiter',
    labelClass: 'labelJupiter',
    imageClass: 'ellipseJupiter',
    color: '#D8A27A',
    orbitRadius: 10.5,
    orbitSpeed: 0.25,
    orbitColor: '#D8A27A',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    label: 'сатурн',
    texturePath: '/assets/textures/8k_saturn.jpg',
    position: 64,
    hasRings: true,
    ringTexturePath: '/assets/textures/8k_saturn_ring_alpha.png',
    scale: 1.1,
    displayScale: 1.6,
    infoScale: 1.4,
    infoDistance: 5.5,
    switchClass: 'planetSwitchSaturn',
    labelClass: 'labelSaturn',
    imageClass: 'extraImageSaturn',
    color: '#E0BB87',
    orbitRadius: 13.0,
    orbitSpeed: 0.18,
    orbitColor: '#E0BB87',
  },
  {
    id: 'uranus',
    name: 'Uranus',
    label: 'уран',
    texturePath: '/assets/textures/2k_uranus.jpg',
    position: 73.33,
    hasRings: true,
    ringInnerRadius: 1.1,
    ringOuterRadius: 1.5,
    ringColor: '#6A7A8A',
    ringOpacity: 0.3,
    ringRotation: [Math.PI / 2, 0, 0.3], 
    scale: 0.95,
    displayScale: 1.2,
    infoScale: 1.3,
    infoDistance: 5.0,
    switchClass: 'planetSwitchUranus',
    labelClass: 'labelUranus',
    imageClass: 'ellipseUranus',
    color: '#4FD0E7',
    orbitRadius: 15.5,
    orbitSpeed: 0.13,
    orbitColor: '#4FD0E7',
  },
  {
    id: 'neptune',
    name: 'Neptune',
    label: 'нептун',
    texturePath: '/assets/textures/2k_neptune.jpg',
    position: 82.67,
    hasRings: true,
    ringInnerRadius: 1.0,
    ringOuterRadius: 1.35,
    ringColor: '#5A6A8A',
    ringOpacity: 0.2,
    ringRotation: [0.15, 0, 0.15],
    scale: 0.95,
    displayScale: 1.2,
    infoScale: 1.3,
    infoDistance: 5.0,
    switchClass: 'planetSwitchNeptune',
    labelClass: 'labelNeptune',
    imageClass: 'ellipseNeptune',
    color: '#4169E1',
    orbitRadius: 18.0,
    orbitSpeed: 0.1,
    orbitColor: '#4169E1',
  },
  {
    id: 'moon',
    name: 'Moon',
    label: 'луна',
    texturePath: '/assets/textures/8k_moon.jpg',
    position: 92,
    scale: 0.7,
    displayScale: 0.5,
    infoScale: 1.5,
    infoDistance: 4.0,
    isMoon: true,
    switchClass: 'planetSwitchMoon',
    labelClass: 'labelMoon',
    imageClass: 'ellipseMoon',
    color: '#CCCCCC',
    orbitRadius: 2.0,
    orbitSpeed: 0.8,
    orbitColor: '#CCCCCC',
  },
];